# -*- coding: utf-8 -*-
"""idea.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAVCLfqLKvs0cWL2WA6okDzhoV8Lb8nq
"""

import streamlit as st
import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

def sistema(t, y, r, a, b, d):
    T, I = y
    dTdt = r * T - a * T * I
    dIdt = b * T * I - d * I
    return [dTdt, dIdt]

def main():
    st.title("Modelo simple de tumor e inmunidad")

    r = st.slider('Proliferación tumoral', 0.1, 2.0, 1.0)
    a = st.slider('Muerte tumoral', 0.1, 2.0, 1.0)
    b = st.slider('Proliferación células inmunes', 0.01, 1.0, 0.1)
    d = st.slider('Muerte células inmunes', 0.01, 1.0, 0.1)
    T0 = st.slider('Número de células iniciales (tumor)', 0.1, 5.0, 1.0)
    I0 = st.slider('Número de células iniciales (sistema inmune)', 0.1, 5.0, 1.0)
    tiempo = st.slider('Tiempo', 20, 300, 100)

    sol = solve_ivp(sistema, [0, tiempo], [T0, I0], args=(r, a, b, d), t_eval=np.linspace(0, tiempo, 1000))
    t = sol.t
    T, I = sol.y

    fig, ax = plt.subplots()
    ax.plot(t, T, label='Tumor (T)', color='red')
    ax.plot(t, I, label='Sistema inmune (I)', color='blue')
    ax.set_title('Evolución temporal')
    ax.set_xlabel('Tiempo')
    ax.set_ylabel('Poblaciones')
    ax.legend()
    ax.grid(True)

    st.pyplot(fig)

if __name__ == '__main__':
    main()
